/*
 * bin2inc - Emit C array from binary file (like xxd -i).
 * Usage: bin2inc input.bin output.inc [var_name]
 * Default var_name: basename with . replaced by _, e.g. dillo_demo_bosx
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char* basename(const char* path) {
    const char* p = strrchr(path, '/');
    if (p) return p + 1;
    p = strrchr(path, '\\');
    if (p) return p + 1;
    return path;
}

static void to_var_name(char* out, const char* name, size_t cap) {
    size_t i = 0;
    while (name[i] && i + 1 < cap) {
        out[i] = (name[i] == '.' || name[i] == '-') ? '_' : name[i];
        i++;
    }
    out[i] = '\0';
}

int main(int argc, char** argv) {
    if (argc < 3) {
        fprintf(stderr, "Usage: bin2inc input.bin output.inc [var_name]\n");
        return 1;
    }

    FILE* f = fopen(argv[1], "rb");
    if (!f) {
        fprintf(stderr, "bin2inc: cannot open %s\n", argv[1]);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 0 || sz > 16 * 1024 * 1024) {
        fclose(f);
        fprintf(stderr, "bin2inc: invalid file size\n");
        return 1;
    }

    unsigned char* buf = (unsigned char*)malloc((size_t)sz);
    if (!buf) {
        fclose(f);
        return 1;
    }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (n != (size_t)sz) {
        free(buf);
        return 1;
    }

    char var[128];
    if (argc >= 4) {
        strncpy(var, argv[3], sizeof(var) - 1);
        var[sizeof(var) - 1] = '\0';
    } else {
        to_var_name(var, basename(argv[1]), sizeof(var));
    }

    FILE* out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "bin2inc: cannot write %s\n", argv[2]);
        free(buf);
        return 1;
    }

    fprintf(out, "/* Generated by bin2inc - do not edit */\n");
    fprintf(out, "static const unsigned char %s[] = {\n", var);
    for (size_t i = 0; i < n; i++) {
        if (i % 12 == 0) fputs("    ", out);
        fprintf(out, "0x%02x", buf[i]);
        if (i + 1 < n) fputc(',', out);
        if ((i + 1) % 12 == 0 || i + 1 == n) fputc('\n', out);
    }
    fprintf(out, "};\n");

    fclose(out);
    free(buf);
    return 0;
}
