/*
 * embed_ca_pem - Emit ca_bundle.c from PEM file (Mozilla CA bundle).
 * Replaces embed_ca_pem.py. No Python required.
 *
 * Usage: embed_ca_pem input.pem output.c
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char** argv) {
    if (argc != 3) {
        fprintf(stderr, "Usage: embed_ca_pem input.pem output.c\n");
        return 1;
    }

    FILE* f = fopen(argv[1], "rb");
    if (!f) {
        fprintf(stderr, "embed_ca_pem: cannot open %s\n", argv[1]);
        return 1;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz <= 0 || sz > 1024 * 1024) {
        fclose(f);
        fprintf(stderr, "embed_ca_pem: invalid file size\n");
        return 1;
    }

    unsigned char* buf = (unsigned char*)malloc((size_t)sz);
    if (!buf) {
        fclose(f);
        return 1;
    }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (n != (size_t)sz) {
        free(buf);
        return 1;
    }

    FILE* out = fopen(argv[2], "w");
    if (!out) {
        fprintf(stderr, "embed_ca_pem: cannot write %s\n", argv[2]);
        free(buf);
        return 1;
    }

    fprintf(out, "/* Generated by scripts/embed_ca_pem.c - Mozilla CA bundle */\n");
    fprintf(out, "#include <stddef.h>\n");
    fprintf(out, "const char lard_ca_bundle_pem[] =\n");
    for (size_t i = 0; i < n; ) {
        fputs("  \"", out);
        for (int j = 0; j < 16 && i < n; j++, i++) {
            fprintf(out, "\\x%02x", buf[i]);
        }
        fputs("\"\n", out);
    }
    fprintf(out, "  \"\";\n");
    fprintf(out, "const size_t lard_ca_bundle_pem_len = sizeof(lard_ca_bundle_pem) - 1u;\n");
    fclose(out);
    free(buf);
    printf("Wrote %s\n", argv[2]);
    return 0;
}
