# deps.mk - small dependency registry included by Makefile.
#
# LardOS is 64-bit only. Keep lower layers before features that use them:
#
#   rtl8139/drfl -> net.c -> lard_tls.c -> HTTPS fetch path
#
# No third_party TLS library is part of the build.

KERNEL_LIBS := hash ringbuf base64

# LDLL libraries generated by scripts/mkldll.
LDLL_LIBS := lard gui lafillo ldll hash base64 fs
